function [PhyPar,SysPar] = ParameterInitialization(Freqc,NumberofCarrier,NumberofSymbol, ...
    NumberofAntennahorizon, NumberofAntennavertical, NumberofTarget, NumberofScatter, NumberofBD, ...
    NumberofUser, Range, HorSpacingRate, VerSpacingRate , Subcarrierspacing...
    )
PhyPar = struct(...
    'StrVecfun', @(r) exp(1j*2*pi*r), ...
    'Freqc', Freqc, ...
    'c', 3e8, ...
    'NumberofCarrier', NumberofCarrier, ...
    'NumberofSymbol', NumberofSymbol, ...
    'NumberofAntennahorizon', NumberofAntennahorizon, ...
    'NumberofAntennavertical', NumberofAntennavertical, ...
    'Subcarrierspacing', Subcarrierspacing);

PhyPar.lambda = PhyPar.c/PhyPar.Freqc;
PhyPar.Spacinghorizon = HorSpacingRate * PhyPar.lambda;
PhyPar.Spacingvertical = VerSpacingRate * PhyPar.lambda;

SysPar = struct( ...
    'NumberofTarget', NumberofTarget, ...
    'NumberofScatter', NumberofScatter, ...
    'NumberofUser', NumberofUser, ...
    'NumberofBD', NumberofBD, ...
    'Range', Range);
end

